frr version 10.2
frr defaults traditional
hostname r1
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.1.1.1/32
!
router bgp 65001
 bgp router-id 10.1.1.1
 no bgp ebgp-requires-policy
 neighbor 172.30.0.3 remote-as 65002
 neighbor 172.30.0.3 description to-r2
 !
 address-family ipv4 unicast
  network 10.1.1.1/32
  neighbor 172.30.0.3 activate
 exit-address-family
!
router ospf
 ospf router-id 10.1.1.1
 network 172.30.0.0/24 area 0
!
line vty
!
