frr version 10.2
frr defaults traditional
hostname r4
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.4.4.4/32
!
router ospf
 ospf router-id 10.4.4.4
 network 172.31.0.0/24 area 0
!
line vty
!
